import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// components
import Common from "./_components/common/common";

// NoSSR でやりたい時 ------------------------------------------------------------------
// import dynamic from "next/dynamic";
// const Header = dynamic(() => import('./_components/header/header'), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arknight Character Sheets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Common />
        <div className="p-4 sm:ml-64">
          <div className="p-4 dark:border-gray-700 mt-14">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
